---
title: "Unit_9_Assignment"
author: "Matt Chinchilla"
date: "7/6/2019"
output: html_document
keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
#Libraries
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(sjPlot)
library(sjlabelled)
library(sjmisc)
```


#### A. Clean an prepare the Data:
```{r}
#Create Data frame for Beers.csv data
Beers <- read.csv("./Beers.csv")

#Create data frame for Breweries.cvs
Breweries <- read.csv("./Breweries.csv")

#Merge into new dataframe BeersBreweries
BeersBreweries <- inner_join(Beers,Breweries, by = c("Brewery_id" = "Brew_ID"))

#Rename columns from Name.x and Name.y to Beer_Name and Brewery_Name 
names(BeersBreweries)[1] <- c("Beer_Name")
names(BeersBreweries)[8] <- c("Brewery_Name")

#trim the white space in state abbreviations 
BeersBreweries$State <- trimws(BeersBreweries$State)

#Create subset of BeersBreweries with only Texas and Colorado Breweries 
beerCOTX <- filter(BeersBreweries, State == c("TX","CO"))

#Omit all rows from beerCOTX with null value for IBU
beerCOTX <- beerCOTX %>% na.omit(beerCOTX$IBU)

#Arrange Rows in ascending order by IBU
beerCOTX <- beerCOTX %>% arrange(IBU)

#View beerCOTX
kable(head(beerCOTX)) %>% kable_styling(bootstrap_options = "striped")
```

#### B. Create Initial plots of the data
```{r}
#Plot IBU and ABV for all values in beerCOTX and assign to variable p
p <- ggplot(beerCOTX, aes(IBU, ABV)) + geom_point()

#Split the previous plot into two based on state
p + facet_grid(State ~.)
```


#### C. Model Texas and Colorado Data
```{r}
#Split beerCOTX by state

#Texas Breweries
beerTX <- filter(beerCOTX, State == "TX")

#Calculate coeficients
lmtx <- lm(ABV ~ IBU, data = beerTX)

#Grab coefficients data
coefs <- coef(lmtx)

#Plot using base plot function.
plot(beerTX$IBU, beerTX$ABV, pch=20, col = "red", xlab = "IBU", ylab = "ABV", main = "ABV vs IBU Texas")
abline(coefs[1], coefs[2], col = "blue")

summary(lmtx)
```
```{r}
#Split beerCOTX by state

#Colorado Breweries
beerCO <- filter(beerCOTX, State == "CO")

#Calculate coeficients
lmco <- lm(ABV ~ IBU, data = beerCO)

#Grab coefficients data
coefs1 <- coef(lmco)

#Plot using base plot function.
plot(beerCO$IBU, beerCO$ABV, pch=20, col = "red", xlab = "IBU", ylab = "ABV", main = "ABV vs IBU Colorado")
abline(coefs1[1], coefs1[2], col = "blue")

summary(lmco)
```
#### D. Gain inference from the model
```{r}
#Parameter estimate table TX
tab_model(lmtx)

#Parameter estimate table CO
tab_model(lmco)
```